version: '3.8'
services:
  debug:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace:cached
    network_mode: bridge
    ports:
      - '8000:8000' # 必要なサービスごとに開放
      - '1883:1883'
      - '5201:5201'
    cap_add:
      - NET_ADMIN # tcpdump などに必要
    tty: true # 常駐

